### ISSUE TITLE
attempt to reproduce results

### ISSUE THREAD

**Issue by akshayMpatel** [XueyiDong/LongReadRNA#1]
I was attempting to reproduce results for flames (NSC and sequins) analyses, but there are a couple of issues I would like to request help with.  

1) gffcompare between my attempt to reproduce the flames NSC results and `./NSC/flames/results/isoform_annotated.filtered.gff3` are significantly different (ie `Intron chain level:    62.4 (Sensitivity)    |    36.5 (Precision)   |`).  I noticed `./NSC/flames/config_bulk_nanopore.json` file was last updated ~7 months ago but the `./NSC/flames/run_flames.sh` file and the original gff3 results file were updated less than 1 month ago.  Does this config file correspond to the posted results, as I would expect almost 100% agreement for sensitivity and precision?  If not, could you please provide files that correspond to the results you posted in the paper?

2) Could you also please provide the `config_sequin.json` used for the flames sequins run?  

Many Thanks!

**Comment by XueyiDong** [comment]
Hi @akshayMpatel 

Thanks for rerunning the analysis.

We haven't changed the config file recently. The most possible reason for the discordance of result is that we have rebasecalled our data and updated the fastq files on GEO in last November. Can you check whether you are using the latest version of our data?

I have also added `config_sequin.json`. Sorry I forgot to add it into this repo.

Best,
Xueyi

**Comment by akshayMpatel** [comment]
Hi @XueyiDong

Thanks for your response.  That's good to know.  I downloaded the data from
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151984 after Feb.
2021 and the last update says 05. Nov. 2020, so I think it's right.

We reran flames on the NSC data using just raw reads and no bam file as in
.../NSC/flames/run_flames/sh and better results from gffcompare (Intron
chain level:  85.6   |  73.1  |), but it is still not close to an exact
match.  Did you supply a bam file from an external minimap call on the
reads?  And if so, what minimap parameters did you use?

Many thanks for uploading the config file for sequins!

Best,
Akshay

Am Do., 1. Apr. 2021 um 04:19 Uhr schrieb Xueyi Dong <
***@***.***>:

**Comment by XueyiDong** [comment]
Hi @akshayMpatel ,

I hope you are doing well. I'm not sure if you are still interested in it as this issue has been raised almost one year ago, and I apologize for the late reply.

We were trying to find out why it happened. Recently we found out there is a bug in FLAMES that can cause isoforms in the annotation marked as novel incorrectly. This issue happens erratically that the final output may be different when computing environment (i.e. different machine) changes. This can probably be the reason why the GFF3 you got is different from ours. Our FLAMES developers are working on fixing this bug as soon as possible.

Thanks again for paying attention to our research. 

Best,
Xueyi
