### ISSUE TITLE
flames fails on k8 paftools.js gff2bed conversion of rnasequin_annotation_2.4.gtf to bed12

### ISSUE THREAD

**Issue by akshayMpatel** [XueyiDong/LongReadRNA#2]
I get the following error when attempting to reproduce run_flames.sh results for the sequins data
```
Command '['.../k8 .../paftools.js gff2bed .../sequins/annotations/rnasequin_annotation_2.4.gtf > \
.../tmp.splice_anno.bed12']' returned non-zero exit status 1
```

On further inspection, a manual attempt to convert the .gtf file, results in following error.  
```
.../paftools.js:1593: ReferenceError: name is not defined
                        exons.push([t[0], t[3], t[4], t[6], id, type, name, tname]);
                                                 ^
ReferenceError: name is not defined
    at paf_gff2bed (.../paftools.js:1593:50)
    at main (.../paftools.js:2517:29)
    at .../paftools.js:2534:1
```

The .gtf seems not to be in proper format.  Can you provide the properly formatted file?  

Many thanks

**Comment by XueyiDong** [comment]
Hi @akshayMpatel ,

Thanks for reading our paper and rerunning our pipeline. 

I've met the same issue before. The author of FLAMES has made some changes to `paftools.js` to make it compatible with gtf/gff files formatted in different ways. I've uploaded our edited version. Please use it to substitute the original `paftools.js` in minimap2. Hopefully this works for you as well.

Cheers,
Xueyi

**Comment by akshayMpatel** [comment]
Hi @XueyiDong,

Ah okay, many thanks.  Do you know if I can replace the paftools.js without
compromising any of the other previous functionality?

Cheers,
Akshay

Am Do., 1. Apr. 2021 um 04:07 Uhr schrieb Xueyi Dong <
***@***.***>:

**Comment by XueyiDong** [comment]
Hi @akshayMpatel ,

I think you can.

Cheers,
Xueyi
