### ISSUE TITLE
interpreting NSC flames count file

### ISSUE THREAD

**Issue by akshayMpatel** [XueyiDong/LongReadRNA#3]
Hello @XueyiDong, 

Could you please quickly verify which counts are wild-type and gene-null in ./NSC/flames/results/pseudo_barcode_annotation.csv? 

I presume
wild-type : barcode07 barcode{10..13}
gene-knockout : barcode{15..17}

Many thanks,
Akshay

**Comment by XueyiDong** [comment]
Hi Akshay,

Barcode 07, 12, 13, 15, 16 are wild-type, and barcode 10, 11 and 17 are gene knockout.

Barcode 07 and 13 are the same sample but sequenced in different batches.

Cheers,
Xueyi
